name: Run

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  run:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 10.15.0
        cache: 'npm'
    - name: Run
      env:
        SLACK_POST_URL: ${{ secrets.SLACK_POST_URL }}
        SLACK_GITHUB_TOKEN: ${{ secrets.SLACK_GITHUB_TOKEN }}
        SLACK_GITHUB_USER: ${{ secrets.SLACK_GITHUB_USER }}
      run: make
